baseURL = 'https://sf.yoyoclub.info/'
languageCode = 'en-us'
title = 'SF Yo-Yo Club'
theme = 'lynx'
params.description = 'Yo-yo club meetings and events in San Francisco'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[params.author]
  name = "SF Yo-Yo Club"
  image = "profile.jpg"
  headline = ''
  calendarLink = "https://calendar.google.com/calendar/embed?src=sfyoyoclub%40gmail.com&ctz=America%2FLos_Angeles"
  extraCalSources = [
    { id = "spindoxyoyo@gmail.com", color = "#9e69af" },
    { id = "bayareayoyoclub@gmail.com", color = "#B78727" }, # 49ers gold hex code
    { id = "eastbayyoyo@gmail.com", color = "#003831" }, # oakland a's green hex code
  ]
  links = [
    { bayarea = { href = "https://bayarea.yoyoclub.info", text = "Bay Area Yo-Yo Clubs", icon = "link" } },
#    { instagram = { href = "https://instagram.com/{{ instagram }}" } },
#    { facebook = { href = "https://facebook.com/{{ facebook }}" } },
#    { discord = "{{ discord }}" },
#    { gcal = { href = "{{ calendarLink }}", text = "Calendar", icon = "google" }}
  ]

[markup.highlight]
  noClasses = false
