baseURL = 'https://bayarea.yoyoclub.info/'
languageCode = 'en-us'
title = 'Bay Area Yo-Yo'
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[params.author]
  #name = "Bay Area"
  image = "profile.webp"
  headline = 'Meta list of yo-yo clubs in Bay Area + miscellaneous non-club events.'
  calendarLink = "https://calendar.google.com/calendar/embed?src=bayareayoyoclub%40gmail.com&ctz=America%2FLos_Angeles"
  extraCalSources = [
    { id = "spindoxyoyo@gmail.com", color = "#9e69af" },
    { id = "sfyoyoclub@gmail.com", color = "#f76024" }, # sf giants orange hex code
    { id = "eastbayyoyo@gmail.com", color = "#003831" }, # oakland a's green hex code
  ]
  links = [
    { spindox = { href = "https://spindox.yoyoclub.info", text = "Spindox (Peninsula)", icon = "link" } },
    { eastbay = { href = "#", text = "East Bay Yo-Yo Club", icon = "link"}},
    { sf = { href = "https://sf.yoyoclub.info", text = "SF Yo-Yo Club", icon = "link"}},
  ]

[markup.highlight]
  noClasses = false
