baseURL = 'https://{{ clubShortName }}.yoyoclub.info/'
languageCode = 'en-us'
title = '{{ clubName }}'
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[params.author]
  name = "{{ clubName }}"
  image = "profile.jpg"
  headline = '{{ clubHeadline }}'
  calendarLink = "{{ calendarLink }}"
  #extraCalendarSources = ["{{extraCalendarSources}}"]
  links = [
    { a_link = { href = "https://example.com", text = "Example", icon = "link" } },
    { instagram = { href = "https://instagram.com/{{ instagram }}" } },
    { facebook = { href = "https://facebook.com/{{ facebook }}" } },
    { discord = "{{ discord }}" },
    { gcal = { href = "{{ calendarLink }}", text = "Calendar", icon = "google" }}
  ]

[markup.highlight]
  noClasses = false
