baseURL = 'https://blono.yoyoclub.info/'
languageCode = 'en-us'
title = 'Blo_No Yoyo'
theme = 'lynx'
params.description = 'Central Illinois (Bloomington-Normal) Yoyo club'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[params.author]
  name = "Blo_No Yoyo"
  image = "profile.jpg"
  headline = 'Central Illinois (Bloomington-Normal) Yoyo Club'
  calendarLink = "https://calendar.google.com/calendar/embed?src=21e626c4b66ee433386c81ab29682188f8d158a42f4858667dcc449a55a9ac31%40group.calendar.google.com&ctz=America%2FChicago"
  #extraCalendarSources = ["{{extraCalendarSources}}"]
  links = [
    { instagram = { href = "https://www.instagram.com/blono_il_yoyo_club_" } },
    { gcal = { href = "https://calendar.google.com/calendar/u/0?cid=MjFlNjI2YzRiNjZlZTQzMzM4NmM4MWFiMjk2ODIxODhmOGQxNThhNDJmNDg1ODY2N2RjYzQ0OWE1NWE5YWMzMUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t", text = "Calendar", icon = "google" }}
#    { a_link = { href = "https://example.com", text = "Example", icon = "link" } },
#    { facebook = { href = "https://facebook.com/{{ facebook }}" } },
#    { discord = "{{ discord }}" },
  ]

[markup.highlight]
  noClasses = false
