baseURL = 'https://blono.yoyoclub.info/'
languageCode = 'en-us'
title = 'Blo_No Yoyo'
theme = 'lynx'
params.description = 'Central Illinois (Bloomington-Normal) Yoyo club'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[params.author]
  name = "Blo_No Yoyo"
  image = "profile.jpg"
  headline = 'Central Illinois (Bloomington-Normal) Yoyo Club'
  #calendarLink = "{{ calendarLink}}"
  #extraCalendarSources = ["{{extraCalendarSources}}"]
  links = [
    { instagram = { href = "https://www.instagram.com/blono_il_yoyo_club_" } },
#    { a_link = { href = "https://example.com", text = "Example", icon = "link" } },
#    { facebook = { href = "https://facebook.com/{{ facebook }}" } },
#    { discord = "{{ discord }}" },
  ]

[markup.highlight]
  noClasses = false
