baseURL = 'https://cinci.yoyoclub.info/'
languageCode = 'en-us'
title = 'Cinci Yoyo Club'
theme = 'lynx'
params.description = 'Cinci Yoyo Club welcomes throwers of all skill levels from the Tri-state area'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[params.author]
  name = "Cinci Yoyo Club"
  image = "profile.jpg"
  headline = 'Cinci Yoyo Club welcomes throwers of all skill levels from the Tri-state area'
  calendarLink = "https://calendar.google.com/calendar/embed?src=21e626c4b66ee433386c81ab29682188f8d158a42f4858667dcc449a55a9ac31%40group.calendar.google.com&ctz=America%2FNew_York"
  #extraCalendarSources = ["{{extraCalendarSources}}"]
  links = [
    { instagram = { href = "https://www.instagram.com/cinciyoyoclub" } },
    { facebook = { href = "https://www.facebook.com/groups/1783533042063397/" } },
    { discord = "https://discord.gg/E8PVzt9ngG" },
    { gcal = { href = "https://calendar.google.com/calendar/u/0?cid=MjFlNjI2YzRiNjZlZTQzMzM4NmM4MWFiMjk2ODIxODhmOGQxNThhNDJmNDg1ODY2N2RjYzQ0OWE1NWE5YWMzMUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t", text = "Calendar", icon = "google" }}
    #{ a_link = { href = "https://example.com", text = "Example", icon = "link" } },
    #{ gcal = { href = "{{ calendarLink }}", text = "Calendar", icon = "google" }}
  ]

[markup.highlight]
  noClasses = false
